- type: entity
  id: PrinterDocMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: entity-printerdocmachinecircuitboard-name
  description: entity-printerdocmachinecircuitboard-description
  components:
    - type: MachineBoard
      prototype: PrinterDoc
      requirements:
        MatterBin: 3
        Manipulator: 1
      materialRequirements:
        Glass: 1
