- type: entity
  parent: CrateSecgear
  id: CrateSecurityGrenadeBarrier
  name: entity-cratesecuritygrenadebarrier-name
  description: entity-cratesecuritygrenadebarrier-description
  components:
  - type: StorageFill
    contents:
      - id: GrenadeBarrier
        amount: 4
