- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleLoneAbductor
  name: entity-mindroleloneabductor-name
  components:
  - type: MindRole
    exclusiveAntag: true
    antagPrototype: LoneAbductorAntag
  - type: Abductor

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleAbductorVictim
  name: entity-mindroleabductorvictim-name
  components:
  - type: MindRole
    antagPrototype: AbductorVictimAntag
  - type: AbductorVictim
