- type: startingGear
  id: RadioGuardGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitLawyerBlack
    shoes: ClothingShoesBootsLaceup
    id: SyndiListeningPostPDA
    ears: ClothingHeadsetAltSyndicate
    mask: ClothingMaskGasSyndicate
    eyes: ClothingEyesHudSyndicate
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmorPlateCarrierUnremoveable

- type: entity
  parent: ClothingOuterArmorPlateCarrier
  id: ClothingOuterArmorPlateCarrierUnremoveable
  name: entity-clothingouterarmorplatecarrierunremoveable-name
  suffix: Unremoveable
  description: entity-clothingouterarmorplatecarrierunremoveable-description
  categories: [ HideSpawnMenu ]
  components:
    - type: Unremoveable
