- type: entity
  id: CrateSecurityArmor
  parent: CrateSecgear
  name: entity-cratesecurityarmor-name
  description: entity-cratesecurityarmor-description
  components:
  - type: StorageFill
    contents:
      - id: ClothingOuterArmorPlateCarrier # DeltaV - ClothingOuterArmorBulletproof replaced in favour of plate carrier
        amount: 3

- type: entity
  id: CrateSecurityHelmet
  parent: CrateSecgear
  name: entity-cratesecurityhelmet-name
  description: entity-cratesecurityhelmet-description
  components:
  - type: StorageFill
    contents:
      - id: ClothingHeadHelmetBasic
        amount: 3

- type: entity
  id: CrateSecurityNonlethal
  parent: CrateSecgear
  name: entity-cratesecuritynonlethal-name
  description: entity-cratesecuritynonlethal-description
  components:
  - type: StorageFill
    contents:
      - id: WeaponDisabler
        amount: 3
      - id: Stunbaton
        amount: 3
      - id: BoxFlashbang
      - id: Flash
        amount: 3
#      - Pepperspray
    # WWDP launcher & more utility grenades
      - id: WeaponSecurityRiotLauncher
      - id: GrenadeStinger
        amount: 2
      - id: TearGasGrenade
        amount: 2

- type: entity
  id: CrateSecurityRiot
  parent: CrateSecgear
  name: entity-cratesecurityriot-name
  description: entity-cratesecurityriot-description
  components:
  - type: StorageFill
    contents:
      - id: ClothingOuterArmorARC # DeltaV - ClothingOuterArmorRiot replaced in favour of ARC suit
        amount: 2
      - id: ClothingHeadHelmetRiot
        amount: 2
      - id: WeaponShotgunEnforcerRubber
        amount: 2
      - id: BoxBeanbag
        amount: 2
      - id: RiotShield
        amount: 2
      - id: ClothingMaskGasSecurity
        amount: 2

- type: entity
  id: CrateSecurityHeavyBallisticArmor
  parent: CrateSecgear
  name: entity-cratesecurityheavyballisticarmor-name
  description: entity-cratesecurityheavyballisticarmor-description
  components:
  - type: StorageFill
    contents:
      - id: ClothingOuterArmorBallisticHeavy
        amount: 2
      - id: ClothingHeadHelmetHeavyBallistic
        amount: 2
      - id: RiotBulletShield
        amount: 2
      - id: ClothingMaskGasSecurity
        amount: 2

- type: entity
  id: CrateSecurityHeavyAblativeArmor
  parent: CrateSecgear
  name: entity-cratesecurityheavyablativearmor-name
  description: entity-cratesecurityheavyablativearmor-description
  components:
  - type: StorageFill
    contents:
      - id: ClothingOuterArmorAblativeHeavy
        amount: 2
      - id: ClothingHeadHelmetHeavyAblative
        amount: 2
      - id: RiotLaserShield
        amount: 2
      - id: ClothingMaskGasSecurity
        amount: 2

- type: entity
  id: CrateSecurityHeavySecurityArmor
  parent: CrateSecgear
  name: entity-cratesecurityheavysecurityarmor-name
  description: entity-cratesecurityheavysecurityarmor-description
  components:
  - type: StorageFill
    contents:
      - id: ClothingOuterArmorStandardHeavy
        amount: 2
      - id: ClothingHeadHelmetHeavyStandard
        amount: 2
      - id: ClothingMaskGasSecurity
        amount: 2

- type: entity
  id: CrateSecuritySwat
  parent: CrateSecgear
  name: entity-cratesecurityswat-name
  description: entity-cratesecurityswat-description
  components:
  - type: StorageFill
    contents:
      - id: ClothingOuterArmorSwat
        amount: 2
      - id: ClothingHeadHelmetSwat
        amount: 2
      - id: ClothingMaskGasSwat
        amount: 2
      - id: ClothingHandsGlovesCombat
        amount: 2
      - id: ClothingShoesSwat
        amount: 2

- type: entity
  id: CrateSecuritySupplies
  parent: CrateSecgear
  name: entity-cratesecuritysupplies-name
  description: entity-cratesecuritysupplies-description
  components:
  - type: StorageFill
    contents:
      - id: BoxHandcuff
      - id: BoxSechud
      - id: ClothingBeltSecurityFilled
      - id: ClothingMaskGasSecurity
      - id: BookSecurity # replace with lawbook at some point

- type: entity
  id: CrateRestraints
  parent: CrateSecgear
  name: entity-craterestraints-name
  description: entity-craterestraints-description
  components:
  - type: StorageFill
    contents:
      - id: BoxHandcuff
        amount: 2
      - id: BoxZiptie
        amount: 2

- type: entity
  id: CrateSecurityBiosuit
  parent: CrateSecgear
  name: entity-cratesecuritybiosuit-name
  description: entity-cratesecuritybiosuit-description
  components:
  - type: StorageFill
    contents:
      - id: ClothingOuterBioSecurity
        amount: 2
      - id: ClothingHeadHatHoodBioSecurity
        amount: 2
      - id: ClothingMaskSterile
        amount: 2

- type: entity
  id: CrateSecurityTrackingMindshieldImplants
  name: entity-cratesecuritytrackingmindshieldimplants-name
  description: entity-cratesecuritytrackingmindshieldimplants-description
  parent: CrateSecgear
  components:
  - type: StorageFill
    contents:
      - id: MindShieldImplanter
        amount: 4
      - id: TrackingImplanter
        amount: 4

# Cosmetic Crates
