- type: entity
  id: CrateServiceJanitorialSupplies
  parent: CratePlastic
  name: entity-crateservicejanitorialsupplies-name
  description: entity-crateservicejanitorialsupplies-description
  components:
  - type: StorageFill
    contents:
      - id: MopItem
      - id: MopBucket
      - id: Bucket
        amount: 3
      - id: WetFloorSign
        amount: 2
      - id: Soap
      - id: SprayBottleSpaceCleaner
        amount: 2
      - id: TrashBag
        amount: 2
      - id: Plunger
        amount: 2
      - id: BoxCleanerGrenades

- type: entity
  id: CrateServiceReplacementLights
  parent: CrateGenericSteel
  name: entity-crateservicereplacementlights-name
  description: entity-crateservicereplacementlights-description
  components:
  - type: StorageFill
    contents:
      - id: BoxLighttube
      - id: BoxLightbulb

- type: entity
  id: CrateMousetrapBoxes
  parent: CrateGenericSteel
  name: entity-cratemousetrapboxes-name
  description: entity-cratemousetrapboxes-description
  components:
    - type: StorageFill
      contents:
        - id: BoxMousetrap

- type: entity
  id: CrateServiceSmokeables
  parent: CrateGenericSteel
  name: entity-crateservicesmokeables-name
  description: entity-crateservicesmokeables-description
  components:
  - type: StorageFill
    contents:
      - id: CigCartonGreen
        prob: 0.50
        orGroup: CigCarton1
      - id: CigCartonRed
        orGroup: CigCarton1
      - id: CigCartonBlue
        prob: 0.50
        orGroup: CigCarton2
      - id: CigCartonBlack
        orGroup: CigCarton2
      - id: CigarGoldCase
        prob: 0.05
        orGroup: Cigars
      - id: CigarCase
        orGroup: Cigars
      - id: Matchbox
        amount: 2

- type: entity
  id: CrateServiceTheatre
  parent: CrateGenericSteel
  name: entity-crateservicetheatre-name
  description: entity-crateservicetheatre-description
  components:
  - type: StorageFill
    contents:
    - id: ClothingUniformJumpskirtPerformer
    - id: ClothingShoesBootsPerformer
    - id: ClothingOuterSuitMonkey
    - id: ClothingHeadHatAnimalMonkey
    - id: ClothingNeckCloakMoth
    - id: ClothingMaskClown
    - id: ClothingMaskMime
    - id: ClothingShoesClown
    - id: ClothingUniformJumpskirtJanimaid
    - id: ClothingNeckCloakVoid
    - id: RevolverCapGun
    - id: BarberScissors
    - id: ClothingUniformJumpskirtOldDress
    - id: BikeHorn
    - id: ClownRecorder
    - id: ClothingBeltSuspenders

- type: entity
  id: CrateServiceCustomSmokable
  parent: CrateGenericSteel
  name: entity-crateservicecustomsmokable-name
  description: entity-crateservicecustomsmokable-description
  components:
  - type: StorageFill
    contents:
    - id: PackPaperRolling
    - id: CigaretteFilter
      amount: 8
    - id: GroundTobacco
      amount: 4
    - id: SmokingPipe
    - id: Matchbox

- type: entity
  id: CrateServiceBureaucracy
  parent: CrateGenericSteel
  name: entity-crateservicebureaucracy-name
  description: entity-crateservicebureaucracy-description
  components:
  - type: StorageFill
    contents:
    - id: Paper
      amount: 15
    - id: Pen
      amount: 2
    - id: BoxFolderClipboard
      amount: 2
    - id: HandLabeler
    - id: BoxFolderBlue
    - id: BoxFolderRed
    - id: BoxFolderYellow
    - id: NewtonCradle

- type: entity
  id: CrateServicePersonnel
  parent: CrateCommandSecure
  name: entity-crateservicepersonnel-name
  description: entity-crateservicepersonnel-description
  components:
  - type: StorageFill
    contents:
    - id: BoxPDA
    - id: BoxID

- type: entity
  id: CrateServiceBooks
  parent: CrateGenericSteel
  name: entity-crateservicebooks-name
  description: entity-crateservicebooks-description
  components:
    - type: StorageFill
      contents:
        - id: BookRandom
          amount: 10

- type: entity
  id: CrateServiceGuidebooks
  parent: CrateGenericSteel
  name: entity-crateserviceguidebooks-name
  description: entity-crateserviceguidebooks-description
  components:
    - type: StorageFill
      contents:
      - id: BookSpaceEncyclopedia
      - id: BookTheBookOfControl
      - id: BookBartendersManual
      - id: BookHowToCookForFortySpaceman
      - id: BookLeafLoversSecret
      - id: BookEngineersHandbook
      - id: BookScientistsGuidebook
      - id: BookSecurity
      - id: BookHowToKeepStationClean
      - id: BookHowToRockAndStone
      - id: BookMedicalReferenceBook
      - id: BookHowToSurvive
      - id: BookChemicalCompendium

- type: entity
  id: CrateServiceSodaDispenser
  parent: CrateGenericSteel
  name: entity-crateservicesodadispenser-name
  description: entity-crateservicesodadispenser-description
  components:
    - type: StorageFill
      contents:
      - id: DrinkCoffeeJug
      - id: DrinkColaBottleFull
      - id: DrinkCreamCartonXL
      - id: DrinkDrGibbJug
      - id: DrinkEnergyDrinkJug
      - id: DrinkGreenTeaJug
      - id: DrinkIceJug
      - id: DrinkJuiceLimeCartonXL
      - id: DrinkJuiceOrangeCartonXL
      - id: DrinkLemonLimeJug
      - id: DrinkRootBeerJug
      - id: DrinkSodaWaterBottleFull
      - id: DrinkSpaceMountainWindBottleFull
      - id: DrinkSpaceUpBottleFull
      - id: DrinkSugarJug
      - id: DrinkTeaJug
      - id: DrinkTonicWaterBottleFull
      - id: DrinkWaterMelonJuiceJug

- type: entity
  id: CrateServiceBoozeDispenser
  parent: CrateGenericSteel
  name: entity-crateserviceboozedispenser-name
  description: entity-crateserviceboozedispenser-description
  components:
    - type: StorageFill
      contents:
      - id: DrinkAleBottleFullGrowler
      - id: DrinkBeerGrowler
      - id: DrinkCoffeeLiqueurBottleFull
      - id: DrinkCognacBottleFull
      - id: DrinkGinBottleFull
      - id: DrinkMeadJug
      - id: DrinkRumBottleFull
      - id: DrinkTequilaBottleFull
      - id: DrinkVermouthBottleFull
      - id: DrinkVodkaBottleFull
      - id: DrinkWhiskeyBottleFull
      - id: DrinkWineBottleFull

- type: entity
  id: CrateServiceBox
  parent: CratePlastic
  name: entity-crateservicebox-name
  description: entity-crateservicebox-description
  components:
    - type: StorageFill
      contents:
        - id: BoxCardboard
          amount: 6

- type: entity
  id: CrateJanitorBiosuit
  parent: CratePlastic
  name: entity-cratejanitorbiosuit-name
  description: entity-cratejanitorbiosuit-description
  components:
  - type: StorageFill
    contents:
      - id: ClothingOuterBioJanitor
        amount: 2
      - id: ClothingHeadHatHoodBioJanitor
        amount: 2
      - id: ClothingMaskSterile
        amount: 2

- type: entity
  id: CrateTrashCartFilled
  suffix: Filled
  parent: CrateTrashCart
  components:
    - type: StorageFill
      contents:
          # Creatures
        - id: MobCockroach
          prob: 0.05
        - id: MobMothroach
          prob: 0.03
        - id: MobMouse
          prob: 0.05
          # Food Packaging
        - id: FoodPacketBoritosTrash
          prob: 0.1
        - id: FoodPacketCheesieTrash
          prob: 0.1
        - id: FoodPacketChipsTrash
          prob: 0.1
        - id: FoodPacketSusTrash
          prob: 0.1
        - id: FoodPacketSyndiTrash
          prob: 0.1
        - id: FoodPacketChowMeinTrash
          prob: 0.1
        - id: FoodPacketDanDanTrash
          prob: 0.1
        - id: FoodPacketMRETrash
          prob: 0.1
        - id: FoodPacketPistachioTrash
          prob: 0.1
        - id: FoodPacketSemkiTrash
          prob: 0.1
        - id: FoodPacketRaisinsTrash
          prob: 0.1
          # Cans
        - id: FoodTinBeansTrash
          prob: 0.15
        - id: FoodTinPeachesTrash
          prob: 0.15
        - id: FoodTinMRETrash
          prob: 0.15
          # Cigarette Stuff
        - id: Ash
          prob: 0.15
        - id: CigaretteSpent
          prob: 0.15
          # Bacteria
        - id: FoodBreadMoldySlice
          prob: 0.15
        - id: FoodPizzaMoldySlice
          prob: 0.15
          # Botanical Waste
        - id: TrashBananaPeel
          prob: 0.15
        - id: FoodCornTrash
          prob: 0.15
          # Misc
        - id: DrinkGlass
          prob: 0.15
        - id: BrokenBottle
          prob: 0.15
        - id: LightTubeBroken
          prob: 0.15
        - id: LightBulbBroken
          prob: 0.15
        - id: MobMouseDead
          prob: 0.1
        - id: Syringe
          prob: 0.1
        - id: ShardGlassPlasma
          prob: 0.1

- type: entity
  id: CrateJanitorExplosive
  parent: ClosetJanitorBomb
  name: entity-cratejanitorexplosive-name
  description: entity-cratejanitorexplosive-description
  components:
  - type: StorageFill
    contents:
      - id: ClothingOuterSuitJanitorBomb
        amount: 1
      - id: ClothingHeadHelmetJanitorBombSuit
        amount: 1
