- type: antag
  id: LoneAbductorAntag
  name: antag-loneabductorantag-name
  antagonist: true
  objective: roles-antag-abductor-objective

- type: antag
  id: AbductorVictimAntag
  name: abductor-victim-role-name
  antagonist: true
  objective: roles-antag-abductor-victim
