- type: entity
  id: CrateFishingGoodies
  parent: CratePlastic
  name: entity-cratefishinggoodies-name
  description: entity-cratefishinggoodies-description
  components:
  - type: StorageFill
    contents:
      - id: FishingRod
      - id: FishingRodGoon
      - id: ClothingHeadFishCap
      - id: DrinkBeerBottleFull
